### ISSUE TITLE
Topic not present in metadata after 60000 ms

### ISSUE THREAD

**Issue by MinhTranQuang258** [wso2-extensions/esb-connector-kafka#65]
I am trying to publish a message to Kafka with a very simple configuration as follows:
```
<localEntry key="KAFKA_CONNECTION_1" xmlns="http://ws.apache.org/ns/synapse">
    <kafkaTransport.init>
        <connectionType>kafka</connectionType>
        <keySerializerClass>org.apache.kafka.common.serialization.StringSerializer</keySerializerClass>
        <name>KAFKA_CONNECTION_1</name>
        <valueSerializerClass>org.apache.kafka.common.serialization.StringSerializer</valueSerializerClass>
        <bootstrapServers>localhost:9092</bootstrapServers>
        <poolingEnabled>false</poolingEnabled>
    </kafkaTransport.init>
</localEntry>
```
```
    <kafkaTransport.publishMessages configKey="KAFKA_CONNECTION_1">
        <topic>ei-output</topic>
        <partitionNo>1</partitionNo>
    </kafkaTransport.publishMessages>
```
When my sequence publishes a message, it always gets an error like this:
```
2022-01-24 11:12:12,561 [DEBUG ] clients.producer.KafkaProducer - [Producer clientId=] Exception occurred during message send:
org.apache.kafka.common.errors.TimeoutException: Topic ei-output not present in metadata after 60000 ms.
2022-01-24 11:12:12,602 [ERROR ] carbon.connector.KafkaProduceConnector - Kafka producer connector : Error sending the message to broker
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Topic ei-output not present in metadata after 60000 ms.
	at org.apache.kafka.clients.producer.KafkaProducer$FutureFailure.<init>(KafkaProducer.java:1317) ~[kafka-clients-2.7.1.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:986) ~[kafka-clients-2.7.1.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:886) ~[kafka-clients-2.7.1.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:774) ~[kafka-clients-2.7.1.jar:?]
	at org.wso2.carbon.connector.KafkaProduceConnector.send(KafkaProduceConnector.java:327) ~[1642997422761kafkaTransport-connector-3.1.2.zip/:?]
	at org.wso2.carbon.connector.KafkaProduceConnector.publishMessage(KafkaProduceConnector.java:241) [1642997422761kafkaTransport-connector-3.1.2.zip/:?]
	at org.wso2.carbon.connector.KafkaProduceConnector.connect(KafkaProduceConnector.java:138) [1642997422761kafkaTransport-connector-3.1.2.zip/:?]
	at org.wso2.carbon.connector.core.AbstractConnector.mediate(AbstractConnector.java:32) [org.wso2.carbon.connector.core_4.7.99.jar:?]
	at org.apache.synapse.mediators.ext.ClassMediator.updateInstancePropertiesAndMediate(ClassMediator.java:178) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:97) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.mediators.template.TemplateMediator.mediate(TemplateMediator.java:136) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:170) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:93) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:242) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.mediateFromContinuationStateStack(Axis2SynapseEnvironment.java:820) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:322) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:608) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:207) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) [axis2_1.6.1.wso2v63.jar:?]
	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:298) [synapse-nhttp-transport_2.1.7.wso2v227.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v63.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: org.apache.kafka.common.errors.TimeoutException: Topic ei-output not present in metadata after 60000 ms.
```
I spent the whole day struggling with this problem, and finally, I found out the problem seemed to come from the `<partitionNo>1</partitionNo>` configuration. When I delete this configuration, the Kafka connector has been operating normally. So there may be an error in this configuration

**Comment by arunans23** [comment]
Giving partitionNo as 0 will also work like below.

`<partitionNo>0</partitionNo>`
